version: "3"
services:
  php:
    build: .
    tty: true # for detach in bash terminal
    volumes:
      - .:/var/www/html
    ports:
      - "8086:80"
    environment:
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      SPOTIFY_REDIRECT_URL: ${SPOTIFY_REDIRECT_URL}
      SPOTIFY_USERNAME: ${SPOTIFY_USERNAME}