version: "3"
services:
  php:
    build: .
    tty: true # for detach in bash terminal
    volumes:
      - .:/var/www/html
    ports:
      - "8086:80"
    environment:
      CLIENT_ID: ${CLIENT_ID}
      REDIRECT_URL: ${REDIRECT_URL}